backend:
  name: github
  repo: nakleiderer/kleiderer-site

publish_mode: editorial_workflow

media_folder: "/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "category"
    label: "Category"
    folder: "src/pages/category"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "category" }
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: Tag, name: tag, widget: string}
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "src/pages/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "article" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "published_on", widget: "datetime"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "category"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
        required: false
  - name: "book" # Used in routes, e.g., /admin/collections/blog
    label: "Book" # Used in the UI
    folder: "src/pages/book" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "book" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Byline", name: "byLine", widget: "string"}
      - {label: "Affiliate Link", name: "affiliate_link", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Is Completed", name: "isCompleted", widget: "boolean"}
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "category"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
        required: false
  - name: "software"
    label: "Software"
    folder: "src/pages/software"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "software" }
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Affiliate Link", name: "affiliate_link", widget: "string"}
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "category"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
        required: false