name: Continuous Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build_deploy_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: "12.x"
      - name: Install Dependencies
        run: npm ci --prefix ./site
      - name: Build Site
        run: npm run --prefix ./site build
      - name: Upload Site Artifact
        uses: actions/upload-artifact@v1
        with:
          name: site-dist
          path: site/build/dist
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run --prefix ./site deploy -- --token "$FIREBASE_TOKEN"
        if: github.event_name == 'push' && github.ref == 'master'
